CREATE TABLE DRUGSTORE
(
  ID_DRUGSTORE                  INTEGER         NOT NULL,
  DRUGSTORE_ADDRESS             VARCHAR(256)    NOT NULL,
 CONSTRAINT PK_DRUGSTORE PRIMARY KEY (ID_DRUGSTORE)
);  

COMMIT;

DROP TABLE REQUEST_FROM_CONSIGNMENT;

CREATE TABLE REQUEST_FROM_DRUGSTORE
(
  ID_REQUEST_FROM_DRUGSTORE      INTEGER         NOT NULL,
  ID_REQUEST                     INTEGER         NOT NULL  REFERENCES REQUEST,
  ID_DRUGSTORE                   INTEGER         NOT NULL  REFERENCES DRUGSTORE,
  DRUG_PREVIOUS_COST             DECIMAL(18,4)   NOT NULL,
  DRUG_COUNT                     INTEGER        NOT NULL,
 CONSTRAINT PK_REQUEST_FROM_DRUGSTORE PRIMARY KEY (ID_REQUEST_FROM_DRUGSTORE)
);    

COMMIT;

ALTER TABLE CONSIGNMENT ADD ID_DRUGSTORE INTEGER NOT NULL;

ALTER TABLE CONSIGNMENT ADD
CONSTRAINT FK_CONSIGNMENT FOREIGN KEY (ID_DRUGSTORE) REFERENCES DRUGSTORE;

COMMIT;
