CREATE EXCEPTION INCOMPATIBILITY_ALREADY_EXISTS 'Incompatibility is already exists.';
CREATE EXCEPTION INCOMPATIBILITY_DRUGS_THE_SAME 'Drugs the same.';


CREATE TRIGGER INCOMPATIBILITY_CHECK_DOUBLE FOR INCOMPATIBILITY
    ACTIVE BEFORE INSERT
AS
    DECLARE VARIABLE CHECK_NULL INTEGER;
BEGIN
    CHECK_NULL = NULL;
    CHECK_NULL = ( SELECT INCOMPATIBILITY.ID_INCOMPATIBILITY FROM INCOMPATIBILITY
                   WHERE INCOMPATIBILITY.ID_DRAG_FIRST = NEW.ID_DRAG_FIRST AND INCOMPATIBILITY.ID_DRAG_SECOND = NEW.ID_DRAG_SECOND );

    IF(NOT (CHECK_NULL IS NULL)) THEN
        EXCEPTION INCOMPATIBILITY_ALREADY_EXISTS;

    CHECK_NULL = NULL;
    CHECK_NULL = ( SELECT INCOMPATIBILITY.ID_INCOMPATIBILITY FROM INCOMPATIBILITY
                   WHERE INCOMPATIBILITY.ID_DRAG_FIRST = NEW.ID_DRAG_SECOND AND INCOMPATIBILITY.ID_DRAG_SECOND = NEW.ID_DRAG_FIRST );

    IF(NOT (CHECK_NULL IS NULL)) THEN
        EXCEPTION INCOMPATIBILITY_ALREADY_EXISTS;

    IF(NEW.ID_DRAG_FIRST = NEW.ID_DRAG_SECOND) THEN
        EXCEPTION INCOMPATIBILITY_DRUGS_THE_SAME;
END