#!/bin/bash 
output="$1"
[ "$output" == "" ] && output='types.res'

ls -Rl / 2>/dev/null | awk '{ if ($0 ~ /^\//)  e_path=substr($0, 0, length($0)-1); else { if ($1 ~ /^l/) $(NF-2)=e_path"/"$(NF-2); else { $NF=e_path"/"$NF}  print $0 } }' | grep ^[-dplscb] | sort -k1.1,1.1 | uniq -w1 > $output

exit 0
