#!/bin/bash
efile="$(realpath $1)"
echo Full path: $efile
ls -Rl / 2>/dev/null | awk '{ if ($0 ~ /:$/)  e_path=substr($0, 0, length($0)-1); else { if ($1 ~ /^l/) $(NF-2)=e_path"/"$(NF-2); else { $NF=e_path"/"$NF}  print $0 } }' | grep ^[l] | awk '{ if ("realpath "$9 | getline full_path) { if (full_path ==  "'"$efile"'") print $(NF-2)} close("realpath "$9)}' 
exit 0
