SET NAMES CYRL;

DROP TABLE REQUEST_FROM_DRUGSTORE;
DROP TABLE REQUEST_FROM_CONSIGNMENT;
DROP TABLE REQUEST;
DROP TABLE CONSIGNMENT;
DROP TABLE DRUGSTORE;
DROP TABLE PROVIDER;
DROP TABLE INCOMPATIBILITY;
DROP TABLE CONTRAINDICATION;
DROP TABLE DRUG;
DROP TABLE DISEASE;

COMMIT;

CREATE TABLE DISEASE 
(
  ID_DISEASE                INTEGER         NOT NULL,
  DISEASE_NAME              VARCHAR(256)    NOT NULL,
CONSTRAINT PK_DISEASE PRIMARY KEY (ID_DISEASE)
);

COMMIT;

CREATE TABLE DRUG 
(
  ID_DRUG                INTEGER         NOT NULL,
  DRUG_NAME              VARCHAR(256)    NOT NULL,
  DRUG_SHELF_LIFE        INTEGER     NOT NULL,  
  DRUG_CURRENT_COST      DECIMAL(18,4)   NOT NULL, 
  DRUG_RECIPE_NEEDED     CHAR(1)         NOT NULL,
  CONSTRAINT PK_DRUG PRIMARY KEY (ID_DRUG)
);      

COMMIT;

CREATE TABLE CONTRAINDICATION 
(
  ID_CONTRAINDICATION               INTEGER         NOT NULL,
  ID_DISEASE                        INTEGER         NOT NULL REFERENCES DISEASE,
  ID_DRAG                           INTEGER         NOT NULL REFERENCES DRUG,
 CONSTRAINT PK_CONTRAINDICATION PRIMARY KEY (ID_CONTRAINDICATION)
);       

COMMIT;

CREATE TABLE INCOMPATIBILITY 
(
  ID_INCOMPATIBILITY              INTEGER         NOT NULL,
  ID_DRAG_FIRST                   INTEGER         NOT NULL  REFERENCES DRUG,
  ID_DRAG_SECOND                  INTEGER         NOT NULL  REFERENCES DRUG,
 CONSTRAINT PK_INCOMPATIBILITY PRIMARY KEY (ID_INCOMPATIBILITY)
);           

COMMIT;

CREATE TABLE PROVIDER 
(
  ID_PROVIDER                     INTEGER         NOT NULL,
  PROVIDER_NAME                   VARCHAR(256)    NOT NULL,
 CONSTRAINT PK_PROVIDER PRIMARY KEY (ID_PROVIDER)
);            

COMMIT;

CREATE TABLE CONSIGNMENT 
(
  ID_CONSIGNMENT                  INTEGER         NOT NULL,
  ID_DRAG                         INTEGER         NOT NULL  REFERENCES DRUG,
  ID_PROVIDER                     INTEGER         NOT NULL  REFERENCES PROVIDER,
  CONSIGNMENT_DRAG_COUNT          INTEGER         NOT NULL,
  CONSIGNMENT_ARRIVAL_DATE        TIMESTAMP       NOT NULL, 
  CONSIGNMENT_MANUFACTURE_DATE    TIMESTAMP       NOT NULL,
 CONSTRAINT PK_CONSIGNMENT PRIMARY KEY (ID_CONSIGNMENT)
);         

COMMIT;

CREATE TABLE REQUEST 
(
  ID_REQUEST                     INTEGER         NOT NULL,
  REQUEST_DATE                   TIMESTAMP       NOT NULL,
 CONSTRAINT PK_REQUEST PRIMARY KEY (ID_REQUEST)
);          

COMMIT;

CREATE TABLE REQUEST_FROM_CONSIGNMENT
(
  ID_REQUEST_FROM_CONSIGNMENT    INTEGER         NOT NULL,
  ID_REQUEST                     INTEGER         NOT NULL  REFERENCES REQUEST,
  ID_CONSIGNMENT                 INTEGER         NOT NULL  REFERENCES CONSIGNMENT,
  DRUG_PREVIOUS_COST             DECIMAL(18,4)   NOT NULL,
  DRUG_COUNT                  INTEGER        NOT NULL,
 CONSTRAINT PK_REQUEST_FROM_CONSIGNMENT PRIMARY KEY (ID_REQUEST_FROM_CONSIGNMENT)
);           

COMMIT;

CREATE TABLE DRUGSTORE
(
  ID_DRUGSTORE                  INTEGER         NOT NULL,
  DRUGSTORE_ADDRESS             VARCHAR(256)    NOT NULL,
 CONSTRAINT PK_DRUGSTORE PRIMARY KEY (ID_DRUGSTORE)
);  

COMMIT;

DROP TABLE REQUEST_FROM_CONSIGNMENT;

CREATE TABLE REQUEST_FROM_DRUGSTORE
(
  ID_REQUEST_FROM_DRUGSTORE      INTEGER         NOT NULL,
  ID_REQUEST                     INTEGER         NOT NULL  REFERENCES REQUEST,
  ID_DRUGSTORE                   INTEGER         NOT NULL  REFERENCES DRUGSTORE,
  DRUG_PREVIOUS_COST             DECIMAL(18,4)   NOT NULL,
  DRUG_COUNT                     INTEGER        NOT NULL,
 CONSTRAINT PK_REQUEST_FROM_DRUGSTORE PRIMARY KEY (ID_REQUEST_FROM_DRUGSTORE)
);    

COMMIT;

ALTER TABLE CONSIGNMENT ADD ID_DRUGSTORE INTEGER NOT NULL;

ALTER TABLE CONSIGNMENT ADD
CONSTRAINT FK_CONSIGNMENT FOREIGN KEY (ID_DRUGSTORE) REFERENCES DRUGSTORE;

COMMIT;

