.ALIASES
R_R5            R5(1=0 2=N30635 )
V_V+            V+(+=VCC -=0 )
C_C1            C1(1=N30565 2=N30341 )
V_V-            V-(+=0 -=VEE )
R_R1            R1(1=N30635 2=N30565 )
R_R2            R2(1=0 2=N30341 )
X_D1            D1(+=0 -=N30565 V+=VCC V-=VEE OUT=N30341 )
R_R3            R3(1=N30341 2=N30308 )
R_R4            R4(1=N30308 2=N30635 )
X_D2            D2(+=N30308 -=0 V+=VCC V-=VEE OUT=N30635 )
_    _(VCC=VCC)
_    _(VEE=VEE)
.ENDALIASES
