INSERT INTO INCOMPATIBILITY(ID_INCOMPATIBILITY, ID_DRAG_FIRST, ID_DRAG_SECOND)
VALUES (9, 1, 8);

COMMIT;

INSERT INTO INCOMPATIBILITY(ID_INCOMPATIBILITY, ID_DRAG_FIRST, ID_DRAG_SECOND)
VALUES (10, 8, 1);

COMMIT;

INSERT INTO INCOMPATIBILITY(ID_INCOMPATIBILITY, ID_DRAG_FIRST, ID_DRAG_SECOND)
VALUES (11, 1, 1);

COMMIT;

INSERT INTO INCOMPATIBILITY(ID_INCOMPATIBILITY, ID_DRAG_FIRST, ID_DRAG_SECOND)
VALUES (12, 4, 5);

COMMIT;