INSERT INTO INDICATION(ID_INDICATION, ID_DISEASE, ID_DRUG)
VALUES (13, 4, 9);

COMMIT;

INSERT INTO INDICATION(ID_INDICATION, ID_DISEASE, ID_DRUG)
VALUES (14, 3, 9);

COMMIT;

INSERT INTO INDICATION(ID_INDICATION, ID_DISEASE, ID_DRUG)
VALUES (15, 2, 9);

COMMIT;