INSERT INTO DISEASE(ID_DISEASE, DISEASE_NAME)
VALUES(20, 'Оспа');

COMMIT;

INSERT INTO DISEASE(DISEASE_NAME)
VALUES('Акромегалия');

COMMIT;

INSERT INTO DISEASE(DISEASE_NAME)
VALUES('Алюминоз');

COMMIT;

INSERT INTO DISEASE(ID_DISEASE, DISEASE_NAME)
VALUES(45, 'Ангина');

COMMIT;

INSERT INTO DISEASE(DISEASE_NAME)
VALUES('Анурия');

COMMIT;