CREATE SEQUENCE DISEASE_GENERATOR;
ALTER SEQUENCE DISEASE_GENERATOR RESTART WITH 5;

CREATE TRIGGER DISEASE_AUTOINCREMENT FOR DISEASE
    ACTIVE BEFORE INSERT POSITION 0
AS
    DECLARE VARIABLE TEMP BIGINT NOT NULL;
BEGIN
   IF(NEW.ID_DISEASE IS NULL) THEN
        NEW.ID_DISEASE = GEN_ID(DISEASE_GENERATOR, 1);
   ELSE
   BEGIN
        TEMP = GEN_ID(DISEASE_GENERATOR, 0);
        IF(TEMP < NEW.ID_DISEASE) THEN
            TEMP = GEN_ID(DISEASE_GENERATOR, NEW.ID_DISEASE - TEMP);
   END

END;