CREATE EXCEPTION CLIENT_CONTAINS_IN_OTHER_TABLE 'It is impossible to modify client, besause he is contains in other table.';


CREATE TRIGGER CLIENT_MODIFY FOR CLIENT
    BEFORE DELETE OR UPDATE
AS
BEGIN
    IF(OLD.ID_CLIENT IN (SELECT REQUEST.ID_CLIENT FROM REQUEST)) THEN
        EXCEPTION CLIENT_CONTAINS_IN_OTHER_TABLE;
END