ALTER TABLE REQUEST_FROM_DRUGSTORE
DROP ID_DRUGSTORE;

COMMIT;

ALTER TABLE REQUEST_FROM_DRUGSTORE
ADD ID_CONSIGNMENT INTEGER NOT NULL;

COMMIT;

ALTER TABLE REQUEST_FROM_DRUGSTORE
ADD CONSTRAINT FK_REQUEST_FROM_DRUGSTORE
FOREIGN KEY (ID_CONSIGNMENT) REFERENCES CONSIGNMENT

COMMIT;

CREATE TABLE CLIENT
(
    ID_CLIENT       INTEGER         NOT NULL,
    CLIENT_NAME     VARCHAR(256)    NOT NULL,
   CONSTRAINT PK_CLIENT PRIMARY KEY (ID_CLIENT)
);

COMMIT;

ALTER TABLE REQUEST
ADD ID_CLIENT INTEGER NOT NULL;

COMMIT;

ALTER TABLE REQUEST
ADD CONSTRAINT FK_REQUEST
FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT;

COMMIT;