CREATE VIEW I1 AS
	SELECT DISEASE.ID_DISEASE, DISEASE.DISEASE_NAME FROM DISEASE
	JOIN INDICATION ON DISEASE.ID_DISEASE = INDICATION.ID_DISEASE
	WHERE INDICATION.ID_DRUG IN (SELECT INCOMPATIBILITY.ID_DRAG_FIRST FROM INCOMPATIBILITY)
	   OR INDICATION.ID_DRUG IN (SELECT INCOMPATIBILITY.ID_DRAG_SECOND FROM INCOMPATIBILITY)
	GROUP BY DISEASE.ID_DISEASE, DISEASE.DISEASE_NAME;