CREATE VIEW I3 AS
	SELECT FIRST 10 SKIP 0 CONSIGNMENT.ID_DRUGSTORE, SUM(CONSIGNMENT.CONSIGNMENT_DRAG_COUNT) AS DRUG_WEIGHT FROM CONSIGNMENT
	GROUP BY CONSIGNMENT.ID_DRUGSTORE
	ORDER BY DRUG_WEIGHT DESC;