CREATE VIEW S6P2 AS
	SELECT PROVIDER.PROVIDER_NAME, SUM(CONSIGNMENT.CONSIGNMENT_DRAG_COUNT) FROM PROVIDER
	JOIN CONSIGNMENT ON PROVIDER.ID_PROVIDER = CONSIGNMENT.ID_PROVIDER
	GROUP BY PROVIDER.PROVIDER_NAME;
	
COMMIT;
