/* Exceptions which used by procedure. */

CREATE EXCEPTION CLIENT_IS_NOT_EXIST 'Client is not exist.';
CREATE EXCEPTION DRUG_IS_NOT_EXIST 'Drug is not exist.';


CREATE PROCEDURE GET_DRUG_COST_BY_CLIENT(ID_DRUG INTEGER NOT NULL, ID_CLIENT INTEGER NOT NULL)
    RETURNS(RESULT_DRUG_COST DECIMAL(18,4) NOT NULL)
AS
    DECLARE VARIABLE CHECK_NULL INTEGER;
    DECLARE VARIABLE COEFF DECIMAL(18,4) NOT NULL;
    DECLARE VARIABLE CLIENT_SUMM DECIMAL(18,4);
    DECLARE VARIABLE DRUG_COST DECIMAL(18,4);
BEGIN

    /* Throw exception if client is not exist. */

    CHECK_NULL = NULL;
    CHECK_NULL = ( SELECT CLIENT.ID_CLIENT FROM CLIENT
                   WHERE CLIENT.ID_CLIENT = :ID_CLIENT );

    IF (CHECK_NULL IS NULL) THEN
        EXCEPTION CLIENT_IS_NOT_EXIST;


    /* Throw exception if drug is not exist. */

    CHECK_NULL = NULL;
    CHECK_NULL = ( SELECT DRUG.ID_DRUG FROM DRUG
                   WHERE DRUG.ID_DRUG = :ID_DRUG );

    IF (CHECK_NULL IS NULL) THEN
        EXCEPTION DRUG_IS_NOT_EXIST;


    /* Getting all money, that client spent. */

    CLIENT_SUMM = NULL;
    CLIENT_SUMM = ( SELECT SUM(REQUEST_FROM_DRUGSTORE.DRUG_PREVIOUS_COST * REQUEST_FROM_DRUGSTORE.DRUG_COUNT) FROM REQUEST_FROM_DRUGSTORE
                    JOIN REQUEST ON REQUEST_FROM_DRUGSTORE.ID_REQUEST = REQUEST.ID_REQUEST
                    JOIN CLIENT ON REQUEST.ID_CLIENT = CLIENT.ID_CLIENT
                    WHERE CLIENT.ID_CLIENT = :ID_CLIENT );


    /* Calculate sale coefficient.  */

    IF (CLIENT_SUMM IS NULL) THEN
        COEFF = 1;
    ELSE IF(CLIENT_SUMM < 10000) THEN
        COEFF = 1;
    ELSE IF(CLIENT_SUMM < 50000) THEN
        COEFF = 0.95;
    ELSE IF(CLIENT_SUMM < 90000) THEN
        COEFF = 0.9;
    ELSE
        COEFF = 0.85;


    /* Calculate result drug cost.  */

    RESULT_DRUG_COST = ( SELECT (DRUG.DRUG_CURRENT_COST * :COEFF) FROM DRUG
                         WHERE DRUG.ID_DRUG = :ID_DRUG );

END;
