/* Exceptions which used by procedure. */

CREATE EXCEPTION PROVIDER_IS_NOT_EXIST 'Provider is not exist.';
CREATE EXCEPTION DRUGSTORE_IS_NOT_EXIST 'Drugstore is not exist.';


CREATE PROCEDURE CREATE_NEW_CONSIGMENTS()
AS
    DECLARE VARIABLE CURRENT_DRUG_ID INTEGER NOT NULL;
    DECLARE VARIABLE CONSIGNMENT_COUNT INTEGER;
    DECLARE VARIABLE REQUEST_COUNT INTEGER;

    DECLARE VARIABLE RESULT_COUNT INTEGER NOT NULL;
    DECLARE VARIABLE RESULT_MANUFACTURE_DATE TIMESTAMP NOT NULL;
    DECLARE VARIABLE RESULT_ARRIVAL_DATE TIMESTAMP NOT NULL;
    DECLARE VARIABLE PROVIDER_ID INTEGER;
    DECLARE VARIABLE DRUGSTORE_ID INTEGER;
BEGIN

     /* Throw exception if provider is not exist. */

    PROVIDER_ID = NULL;
    PROVIDER_ID = ( SELECT FIRST 1 PROVIDER.ID_PROVIDER FROM PROVIDER );

    IF (PROVIDER_ID IS NULL) THEN
        EXCEPTION PROVIDER_IS_NOT_EXIST;


    /* Throw exception if drugstore is not exist. */

    DRUGSTORE_ID = NULL;
    DRUGSTORE_ID = ( SELECT FIRST 1 DRUGSTORE.ID_DRUGSTORE FROM DRUGSTORE );

    IF (DRUGSTORE_ID IS NULL) THEN
        EXCEPTION DRUGSTORE_IS_NOT_EXIST;


    FOR
        /*
            Special table for loop:
                First column - drug_id.
                Second column - count of drugs in all consignments.
                Third column - count of drugs in all requests.
        */
        SELECT
            DRUG.ID_DRUG,
            SUM(BUFFER_CONSIGNMENT.CONSIGNMENT_COUNT) AS CONSIGNMENT_COUNT,
            SUM(BUFFER_REQUEST.REQUEST_COUNT) AS REQUEST_COUNT FROM DRUG
        LEFT JOIN (
            SELECT CONSIGNMENT.ID_DRAG AS ID_DRUG, CONSIGNMENT.ID_CONSIGNMENT AS ID_CONSIGNMENT, SUM(CONSIGNMENT.CONSIGNMENT_DRAG_COUNT) AS CONSIGNMENT_COUNT
            FROM CONSIGNMENT
            GROUP BY CONSIGNMENT.ID_DRAG, CONSIGNMENT.ID_CONSIGNMENT
        ) BUFFER_CONSIGNMENT ON BUFFER_CONSIGNMENT.ID_DRUG = DRUG.ID_DRUG
        LEFT JOIN (
            SELECT REQUEST_FROM_DRUGSTORE.ID_CONSIGNMENT AS ID_CONSIGNMENT, SUM(REQUEST_FROM_DRUGSTORE.DRUG_COUNT) AS REQUEST_COUNT
            FROM REQUEST_FROM_DRUGSTORE
            GROUP BY REQUEST_FROM_DRUGSTORE.ID_CONSIGNMENT
        ) AS BUFFER_REQUEST ON BUFFER_REQUEST.ID_CONSIGNMENT = BUFFER_CONSIGNMENT.ID_CONSIGNMENT
        GROUP BY DRUG.ID_DRUG
        ORDER BY DRUG.ID_DRUG
        INTO :CURRENT_DRUG_ID, :CONSIGNMENT_COUNT, :REQUEST_COUNT
    DO
    BEGIN

        /* Calculate result count of drugs (1000 is minimum). */

        IF(CONSIGNMENT_COUNT IS NULL) THEN
            RESULT_COUNT = 1000;
        ELSE IF(CONSIGNMENT_COUNT - REQUEST_COUNT < 1000) THEN
            RESULT_COUNT = 1000 - (CONSIGNMENT_COUNT - REQUEST_COUNT);
        ELSE
            CONTINUE;

        /* Get current time. */

        RESULT_MANUFACTURE_DATE = ( SELECT CURRENT_TIMESTAMP FROM RDB$DATABASE );
        RESULT_ARRIVAL_DATE = DATEADD(10 DAY TO RESULT_MANUFACTURE_DATE);

        /* Insert consignments into table. */

        INSERT INTO CONSIGNMENT (ID_CONSIGNMENT,  ID_DRAG, ID_PROVIDER, CONSIGNMENT_DRAG_COUNT, CONSIGNMENT_ARRIVAL_DATE, CONSIGNMENT_MANUFACTURE_DATE, ID_DRUGSTORE)
        VALUES (
            (SELECT (MAX(CONSIGNMENT.ID_CONSIGNMENT) + 1) FROM CONSIGNMENT),
            :CURRENT_DRUG_ID,
            :PROVIDER_ID,
            :RESULT_COUNT,
            :RESULT_ARRIVAL_DATE,
            :RESULT_MANUFACTURE_DATE,
            :DRUGSTORE_ID
        );

    END

END;

