CREATE TABLE INDICATION
(
    ID_INDICATION   INTEGER     NOT NULL,
    ID_DISEASE      INTEGER     NOT NULL REFERENCES DISEASE,
    ID_DRUG         INTEGER     NOT NULL REFERENCES DRUG,
    CONSTRAINT PK_INDICATION PRIMARY KEY (ID_INDICATION)
);

COMMIT;