CREATE VIEW I2 AS
	SELECT FIRST 5 SKIP 0 REQUEST.ID_REQUEST, (REQUEST_FROM_DRUGSTORE.DRUG_PREVIOUS_COST * REQUEST_FROM_DRUGSTORE.DRUG_COUNT) AS DRUG_WEIGHT FROM REQUEST
	JOIN REQUEST_FROM_DRUGSTORE ON REQUEST.ID_REQUEST = REQUEST_FROM_DRUGSTORE.ID_REQUEST
	WHERE REQUEST.REQUEST_DATE > '01.01.2013' AND REQUEST.REQUEST_DATE < '01.01.2014'
	ORDER BY DRUG_WEIGHT DESC;