CREATE PROCEDURE S12 AS
BEGIN
	DELETE FROM DRUG
	WHERE DRUG.ID_DRUG IN 
	(
		SELECT DRUG.ID_DRUG FROM DRUG
		WHERE DRUG.ID_DRUG NOT IN (SELECT CONTRAINDICATION.ID_DRAG FROM CONTRAINDICATION)
		AND DRUG.ID_DRUG NOT IN (SELECT CONSIGNMENT.ID_DRAG FROM CONSIGNMENT)
		AND DRUG.ID_DRUG NOT IN (SELECT INCOMPATIBILITY.ID_DRAG FROM INCOMPATIBILITY)
	);
	COMMIT;
END;