CREATE VIEW S6P1 AS
	SELECT ('Contraindication: ' || DISEASE.DISEASE_NAME || ' ' || DRUG.DRUG_NAME) FROM DISEASE
	JOIN CONTRAINDICATION ON DISEASE.ID_DISEASE = CONTRAINDICATION.ID_DISEASE
	JOIN DRUG ON CONTRAINDICATION.ID_DRAG = DRUG.ID_DRUG;

COMMIT;