CREATE PROCEDURE S9 AS
BEGIN
	INSERT INTO DISEASE (ID_DISEASE, DISEASE_NAME) 
	VALUES (100001, 'ОРЗ'); 
	COMMIT;

	INSERT INTO DRUG (ID_DRUG, DRUG_NAME, DRUG_SHELF_LIFE, DRUG_CURRENT_COST, DRUG_RECIPE_NEEDED)
	VALUES (100001, 'Супрадин', 30, 25.0, 0);           
	COMMIT;

	INSERT INTO INCOMPATIBILITY (ID_INCOMPATIBILITY,  ID_DRAG_FIRST, ID_DRAG_SECOND) 
	VALUES (100001, 3, 4);       
	COMMIT;

	INSERT INTO CONTRAINDICATION (ID_CONTRAINDICATION,  ID_DISEASE, ID_DRAG) 
	VALUES (100001, 2, 5);  
	COMMIT;

	INSERT INTO PROVIDER (ID_PROVIDER,  PROVIDER_NAME) 
	VALUES (100001, 'Доктор силач');  
	COMMIT;

	INSERT INTO DRUGSTORE (ID_DRUGSTORE,  DRUGSTORE_ADDRESS) 
	VALUES (100001, 'Санкт-Петербург, ул. Парашютная 12к1'); 
	COMMIT;

	INSERT INTO CONSIGNMENT (ID_CONSIGNMENT,  ID_DRAG, ID_PROVIDER, CONSIGNMENT_DRAG_COUNT, CONSIGNMENT_ARRIVAL_DATE, CONSIGNMENT_MANUFACTURE_DATE, ID_DRUGSTORE)
	VALUES (100001, 8, 3, 1000, '02-10-2011', '02-09-2011', 4);    
	COMMIT;

	INSERT INTO REQUEST (ID_REQUEST,  REQUEST_DATE) 
	VALUES (100001, '03-02-2011');   
	COMMIT;

	INSERT INTO REQUEST_FROM_DRUGSTORE (ID_REQUEST_FROM_DRUGSTORE,  ID_REQUEST, ID_DRUGSTORE, DRUG_PREVIOUS_COST, DRUG_COUNT)
	VALUES (100001, 8, 4, 10.0, 40);    
	COMMIT;
END;
